import { CONTRACTS } from "@/contracts";
import type { Address } from "@/types/contracts";
import type { GovernanceTemplateDefinition } from "@/types/governance";

export const GOVERNANCE_TEMPLATES: GovernanceTemplateDefinition[] = [
  {
    id: "content.setRewardRules",
    category: "content",
    label: "更新奖励规则",
    description: "更新内容奖励的最低票数要求和单票奖励金额。",
    riskLevel: "low",
    target: CONTRACTS.KnowledgeContent as Address,
    functionName: "setRewardRules",
    valueMode: "fixedZero",
    fields: [
      {
        key: "minVotesToReward",
        label: "最少获奖票数",
        type: "uint256",
        required: true,
        placeholder: "例如 10",
        defaultValue: "10",
      },
      {
        key: "rewardPerVote",
        label: "单票奖励",
        type: "tokenAmount",
        required: true,
        placeholder: "例如 0.001",
        defaultValue: "0.001",
      },
    ],
  },
  {
    id: "content.setContentPolicy",
    category: "content",
    label: "更新内容策略",
    description: "更新编辑锁定、投票后删除策略和单内容最大版本数。",
    riskLevel: "medium",
    target: CONTRACTS.KnowledgeContent as Address,
    functionName: "setContentPolicy",
    valueMode: "fixedZero",
    fields: [
      {
        key: "editLockVotes",
        label: "编辑锁定票数",
        type: "uint256",
        required: true,
        placeholder: "例如 1",
        defaultValue: "1",
      },
      {
        key: "allowDeleteAfterVote",
        label: "投票后允许删除",
        type: "boolean",
        required: true,
        defaultValue: false,
      },
      {
        key: "maxVersionsPerContent",
        label: "单内容最大版本数",
        type: "uint256",
        required: true,
        placeholder: "例如 20",
        defaultValue: "20",
      },
    ],
  },
  {
    id: "content.setContentFees",
    category: "content",
    label: "更新内容费用",
    description: "调整内容发布费用和新版本更新费用。",
    riskLevel: "medium",
    target: CONTRACTS.KnowledgeContent as Address,
    functionName: "setContentFees",
    valueMode: "fixedZero",
    fields: [
      {
        key: "registerFee",
        label: "发布费用",
        type: "tokenAmount",
        required: true,
        placeholder: "例如 0.01",
        defaultValue: "0.01",
      },
      {
        key: "updateFee",
        label: "更新费用",
        type: "tokenAmount",
        required: true,
        placeholder: "例如 0.005",
        defaultValue: "0.005",
      },
    ],
  },
  {
    id: "stake.setCooldownSeconds",
    category: "stake",
    label: "更新退出冷却期",
    description: "更新质押退出后的冷却时间。",
    riskLevel: "medium",
    target: CONTRACTS.NativeVotes as Address,
    functionName: "setCooldownSeconds",
    valueMode: "fixedZero",
    fields: [
      {
        key: "cooldownSeconds",
        label: "退出冷却期（秒）",
        type: "uint256",
        required: true,
        placeholder: "例如 3600",
        defaultValue: "3600",
      },
    ],
  },
  {
    id: "stake.setActivationBlocks",
    category: "stake",
    label: "更新质押激活延迟",
    description: "更新质押存入后获得投票权前的等待区块数。",
    riskLevel: "medium",
    target: CONTRACTS.NativeVotes as Address,
    functionName: "setActivationBlocks",
    valueMode: "fixedZero",
    fields: [
      {
        key: "activationBlocks",
        label: "激活延迟（区块）",
        type: "uint256",
        required: true,
        placeholder: "例如 10",
        defaultValue: "10",
      },
    ],
  },
  {
    id: "treasury.setBudget",
    category: "treasury",
    label: "更新金库预算",
    description: "更新金库的预算周期和周期预算额度。",
    riskLevel: "medium",
    target: CONTRACTS.TreasuryNative as Address,
    functionName: "setBudget",
    valueMode: "fixedZero",
    fields: [
      {
        key: "epochDuration",
        label: "预算周期（秒）",
        type: "uint256",
        required: true,
        placeholder: "例如 604800",
        defaultValue: "604800",
      },
      {
        key: "epochBudget",
        label: "周期预算",
        type: "tokenAmount",
        required: true,
        placeholder: "例如 100",
        defaultValue: "100",
      },
    ],
  },
  {
    id: "revenueVault.setFaucetConfig",
    category: "treasury",
    label: "更新 Faucet 补充策略",
    description: "调整 RevenueVault 向 FaucetVault 分账的比例、最小补充金额和自动补充开关。",
    riskLevel: "medium",
    target: CONTRACTS.RevenueVault as Address,
    functionName: "setFaucetConfig",
    valueMode: "fixedZero",
    fields: [
      {
        key: "faucetWallet",
        label: "FaucetVault 地址",
        type: "address",
        required: true,
        placeholder: "0x...",
        defaultValue: (CONTRACTS.FaucetVault as string | undefined) ?? "",
      },
      {
        key: "faucetShareBps",
        label: "Faucet 分成基点",
        type: "uint256",
        required: true,
        placeholder: "例如 3000",
        defaultValue: "3000",
      },
      {
        key: "minFaucetPayout",
        label: "最小补充金额",
        type: "tokenAmount",
        required: true,
        placeholder: "例如 0.5",
        defaultValue: "0.5",
      },
      {
        key: "autoFaucetEnabled",
        label: "自动补充",
        type: "boolean",
        required: true,
        defaultValue: true,
      },
    ],
  },
  {
    id: "faucet.setSigner",
    category: "treasury",
    label: "轮换 Faucet 签名地址",
    description: "更新 Faucet 后端授权使用的签名地址。",
    riskLevel: "high",
    target: CONTRACTS.FaucetVault as Address,
    functionName: "setSigner",
    valueMode: "fixedZero",
    fields: [
      {
        key: "signer",
        label: "新签名地址",
        type: "address",
        required: true,
        placeholder: "0x...",
      },
    ],
  },
  {
    id: "faucet.setClaimConfig",
    category: "treasury",
    label: "更新 Faucet 领取规则",
    description: "调整单次领取金额、余额门槛和领取冷却时间。",
    riskLevel: "medium",
    target: CONTRACTS.FaucetVault as Address,
    functionName: "setClaimConfig",
    valueMode: "fixedZero",
    fields: [
      {
        key: "claimAmount",
        label: "单次领取金额",
        type: "tokenAmount",
        required: true,
        placeholder: "例如 2",
        defaultValue: "2",
      },
      {
        key: "minAllowedBalance",
        label: "余额门槛",
        type: "tokenAmount",
        required: true,
        placeholder: "例如 1",
        defaultValue: "1",
      },
      {
        key: "claimCooldown",
        label: "领取冷却（秒）",
        type: "uint256",
        required: true,
        placeholder: "例如 86400",
        defaultValue: "86400",
      },
    ],
  },
  {
    id: "faucet.setBudgetConfig",
    category: "treasury",
    label: "更新 Faucet 周期预算",
    description: "调整 Faucet 的预算周期和周期总预算。",
    riskLevel: "medium",
    target: CONTRACTS.FaucetVault as Address,
    functionName: "setBudgetConfig",
    valueMode: "fixedZero",
    fields: [
      {
        key: "epochDuration",
        label: "预算周期（秒）",
        type: "uint256",
        required: true,
        placeholder: "例如 86400",
        defaultValue: "86400",
      },
      {
        key: "epochBudget",
        label: "周期预算",
        type: "tokenAmount",
        required: true,
        placeholder: "例如 20",
        defaultValue: "20",
      },
    ],
  },
  {
    id: "governor.setProposalThreshold",
    category: "governor",
    label: "更新提案门槛",
    description: "更新发起治理提案所需的最小门槛。",
    riskLevel: "medium",
    target: CONTRACTS.KnowledgeGovernor as Address,
    functionName: "setProposalThreshold",
    valueMode: "fixedZero",
    fields: [
      {
        key: "proposalThreshold",
        label: "提案门槛",
        type: "tokenAmount",
        required: true,
        placeholder: "例如 100",
        defaultValue: "100",
      },
    ],
  },
  {
    id: "governor.setProposalFee",
    category: "governor",
    label: "更新提案费用",
    description: "调整创建治理提案时需要支付的协议费用。",
    riskLevel: "medium",
    target: CONTRACTS.KnowledgeGovernor as Address,
    functionName: "setProposalFee",
    valueMode: "fixedZero",
    fields: [
      {
        key: "proposalFee",
        label: "提案费用",
        type: "tokenAmount",
        required: true,
        placeholder: "例如 0.05",
        defaultValue: "0.05",
      },
    ],
  },
  {
    id: "governor.setVotingDelay",
    category: "governor",
    label: "更新投票延迟",
    description: "更新提案创建后到开始投票之间的延迟区块数。",
    riskLevel: "low",
    target: CONTRACTS.KnowledgeGovernor as Address,
    functionName: "setVotingDelay",
    valueMode: "fixedZero",
    fields: [
      {
        key: "votingDelay",
        label: "投票延迟（区块）",
        type: "uint256",
        required: true,
        placeholder: "例如 1",
        defaultValue: "1",
      },
    ],
  },
  {
    id: "governor.setVotingPeriod",
    category: "governor",
    label: "更新投票周期",
    description: "更新提案处于投票中的持续区块数。",
    riskLevel: "low",
    target: CONTRACTS.KnowledgeGovernor as Address,
    functionName: "setVotingPeriod",
    valueMode: "fixedZero",
    fields: [
      {
        key: "votingPeriod",
        label: "投票周期（区块）",
        type: "uint256",
        required: true,
        placeholder: "例如 10",
        defaultValue: "10",
      },
    ],
  },
  {
    id: "governor.setLateQuorumVoteExtension",
    category: "governor",
    label: "更新法定人数延长期",
    description: "更新在法定人数较晚达成时追加的投票延长区块数。",
    riskLevel: "medium",
    target: CONTRACTS.KnowledgeGovernor as Address,
    functionName: "setLateQuorumVoteExtension",
    valueMode: "fixedZero",
    fields: [
      {
        key: "lateQuorumVoteExtension",
        label: "法定人数延长期（区块）",
        type: "uint256",
        required: true,
        placeholder: "例如 20",
        defaultValue: "20",
      },
    ],
  },
  {
    id: "governor.updateQuorumNumerator",
    category: "governor",
    label: "更新法定人数分子",
    description: "更新治理法定人数计算中的分子参数。",
    riskLevel: "medium",
    target: CONTRACTS.KnowledgeGovernor as Address,
    functionName: "updateQuorumNumerator",
    valueMode: "fixedZero",
    fields: [
      {
        key: "quorumNumerator",
        label: "法定人数分子",
        type: "uint256",
        required: true,
        placeholder: "例如 4",
        defaultValue: "4",
      },
    ],
  },
  {
    id: "timelock.updateDelay",
    category: "timelock",
    label: "更新时间锁延迟",
    description: "更新 Timelock 的最小执行延迟。",
    riskLevel: "high",
    target: CONTRACTS.TimelockController as Address,
    functionName: "updateDelay",
    valueMode: "fixedZero",
    fields: [
      {
        key: "delaySeconds",
        label: "最小延迟（秒）",
        type: "uint256",
        required: true,
        placeholder: "例如 3600",
        defaultValue: "3600",
      },
    ],
  },
];
