import { BRANDING } from "@/lib/branding";

export const GOVERNANCE_DETAIL_COPY = {
  backToList: "返回提案列表",
  pageTitleFallback: "治理提案",
  pageDescription: "在这里查看提案投票结果、动作摘要，并完成后续治理操作。",
  voteDistributionTitle: "投票分布",
  voteDistributionDescription: "快速查看提案状态、总票数和各选项占比。",
  actionsTitle: "提案动作",
  actionsDescription: "保留每个动作的核心摘要，原始参数按需展开查看。",
  panelTitle: "操作面板",
  panelDescription: "根据提案当前状态完成投票、排队或执行。",
  infoTitle: "提案信息",
  infoDescription: "保留当前提案最常查看的关键信息。",
  explorerTitle: "浏览器",
  explorerDescription: "在区块浏览器中查看该提案交易。",
  loadingActions: "正在加载动作详情...",
  noActionData: "暂无动作数据。",
  noOnchainActions: "该提案不包含任何链上执行动作。",
  proposalEventMissing: "未找到该提案的 ProposalCreated 事件记录。",
  unknownAction: "未识别动作",
  unknownFunction: "unknown",
  summaryLabel: "摘要",
  noSummary: "暂无动作摘要",
  targetContract: "目标合约",
  callValue: "调用值",
  rawCalldata: "原始 calldata",
  currentState: "当前状态",
  totalVotes: "总票数",
  forVotes: "赞成票",
  againstVotes: "反对票",
  abstainVotes: "弃权票",
  forLabel: "赞成",
  againstLabel: "反对",
  abstainLabel: "弃权",
  actionPanelIdle: "当前提案暂时没有可执行的治理操作，请关注状态变化。",
  actionPanelVote: "当前提案处于投票中状态，可以参与赞成、反对或弃权投票。",
  actionPanelQueue: "当前提案已通过投票，可以加入 Timelock 执行队列。",
  actionPanelExecute: "当前提案已排队且等待期结束，可以正式执行。",
  voteFor: "投赞成票",
  voteAgainst: "投反对票",
  voteAbstain: "弃权",
  queueProposal: "加入队列",
  executeProposal: "执行提案",
  info: {
    proposalId: "提案 ID",
    createdBlock: "创建区块",
    voteStart: "投票开始",
    voteEnd: "投票结束",
    actionCount: "动作数量",
    proposer: "提案人",
  },
  browserOpen: `在 ${BRANDING.explorerName} 中查看`,
  errors: {
    connectWallet: "请先连接钱包",
    detailMissingQueue: "提案详情尚未加载，无法执行排队操作。",
    detailMissingExecute: "提案详情尚未加载，无法执行提案。",
    missingTxHash: "尚未加载到创建提案的交易哈希。",
  },
  loading: {
    vote: "提交投票...",
    queue: "正在提交排队交易...",
    execute: "正在提交执行交易...",
    detail: "正在加载提案详情...",
  },
  success: {
    vote: "投票成功",
    queue: "排队交易已提交",
    execute: "执行交易已提交",
  },
  fail: {
    vote: "投票失败",
    queue: "排队失败",
    execute: "执行失败",
  },
  status: {
    actionPrefix(index: number) {
      return `动作 #${index + 1}`;
    },
    proposalEyebrow(proposalId: bigint) {
      return `提案 #${proposalId.toString()}`;
    },
  },
} as const;
