create table if not exists indexer_state (
  id bigint generated by default as identity,
  state_key char(64) not null,
  state_value text not null,
  create_time timestamp not null default current_timestamp,
  update_time timestamp not null default current_timestamp,
  constraint pk_indexer_state primary key (id),
  constraint uk_indexer_state_state_key unique (state_key)
);

create table if not exists content (
  id bigint generated by default as identity,
  content_id bigint not null,
  author_address char(42) not null,
  title text not null,
  description text not null,
  cid text not null,
  latest_version bigint not null default 1,
  vote_count decimal(78,0) not null default 0,
  reward_accrual_count bigint not null default 0,
  is_deleted smallint not null default 0,
  created_block_number bigint not null,
  updated_block_number bigint not null,
  create_time timestamp not null default current_timestamp,
  update_time timestamp not null default current_timestamp,
  constraint pk_content primary key (id),
  constraint uk_content_content_id unique (content_id),
  constraint chk_content_is_deleted check (is_deleted in (0,1))
);

create index if not exists idx_content_author_address
  on content (author_address);

create index if not exists idx_content_updated_block_number
  on content (updated_block_number);

create index if not exists idx_content_is_deleted
  on content (is_deleted);

create table if not exists content_version (
  id bigint generated by default as identity,
  content_id bigint not null,
  version_number bigint not null,
  title text not null,
  description text not null,
  cid text not null,
  block_number bigint not null,
  tx_hash char(66) not null,
  create_time timestamp not null default current_timestamp,
  update_time timestamp not null default current_timestamp,
  constraint pk_content_version primary key (id),
  constraint uk_content_version_content_id_version_number unique (content_id, version_number)
);

create index if not exists idx_content_version_content_id
  on content_version (content_id);

create index if not exists idx_content_version_block_number
  on content_version (block_number);

create table if not exists proposal (
  id bigint generated by default as identity,
  proposal_id char(66) not null,
  proposer_address char(42) not null,
  description text not null,
  state_value bigint,
  vote_start_block bigint,
  vote_end_block bigint,
  eta_second bigint,
  action_count bigint not null default 0,
  created_block_number bigint not null,
  updated_block_number bigint not null,
  tx_hash char(66) not null,
  create_time timestamp not null default current_timestamp,
  update_time timestamp not null default current_timestamp,
  constraint pk_proposal primary key (id),
  constraint uk_proposal_proposal_id unique (proposal_id)
);

create index if not exists idx_proposal_proposer_address
  on proposal (proposer_address);

create index if not exists idx_proposal_created_block_number
  on proposal (created_block_number);

create index if not exists idx_proposal_state_value
  on proposal (state_value);

create table if not exists proposal_action (
  id bigint generated by default as identity,
  proposal_id char(66) not null,
  action_index bigint not null,
  target_address char(42) not null,
  action_value decimal(78,0) not null default 0,
  calldata_hex text not null,
  summary_text text,
  create_time timestamp not null default current_timestamp,
  update_time timestamp not null default current_timestamp,
  constraint pk_proposal_action primary key (id),
  constraint uk_proposal_action_proposal_id_action_index unique (proposal_id, action_index)
);

create index if not exists idx_proposal_action_proposal_id
  on proposal_action (proposal_id);

create table if not exists reward_event (
  id bigint generated by default as identity,
  event_id char(80) not null,
  event_kind char(16) not null,
  content_id bigint,
  author_address char(42),
  beneficiary_address char(42),
  amount decimal(78,0) not null,
  block_number bigint not null,
  log_index bigint not null,
  tx_hash char(66) not null,
  event_time timestamp,
  create_time timestamp not null default current_timestamp,
  update_time timestamp not null default current_timestamp,
  constraint pk_reward_event primary key (id),
  constraint uk_reward_event_event_id unique (event_id)
);

create index if not exists idx_reward_event_beneficiary_address
  on reward_event (beneficiary_address);

create index if not exists idx_reward_event_author_address
  on reward_event (author_address);

create index if not exists idx_reward_event_content_id
  on reward_event (content_id);

create index if not exists idx_reward_event_block_number
  on reward_event (block_number);

create table if not exists user_snapshot (
  id bigint generated by default as identity,
  user_address char(42) not null,
  content_count bigint not null default 0,
  proposal_count bigint not null default 0,
  pending_reward_amount decimal(78,0) not null default 0,
  staked_amount decimal(78,0) not null default 0,
  pending_stake_amount decimal(78,0) not null default 0,
  pending_withdraw_amount decimal(78,0) not null default 0,
  is_active smallint not null default 1,
  create_time timestamp not null default current_timestamp,
  update_time timestamp not null default current_timestamp,
  constraint pk_user_snapshot primary key (id),
  constraint uk_user_snapshot_user_address unique (user_address),
  constraint chk_user_snapshot_is_active check (is_active in (0,1))
);
