alter table content
  add column if not exists version_count bigint not null default 0,
  add column if not exists created_at_second bigint not null default 0,
  add column if not exists last_updated_at_second bigint not null default 0;

alter table content_version
  add column if not exists version_timestamp_second bigint not null default 0;

alter table proposal
  add column if not exists state_value bigint,
  add column if not exists eta_second bigint,
  add column if not exists for_vote_amount decimal(78,0) not null default 0,
  add column if not exists against_vote_amount decimal(78,0) not null default 0,
  add column if not exists abstain_vote_amount decimal(78,0) not null default 0;

create table if not exists system_snapshot (
  id bigint generated by default as identity,
  snapshot_key char(16) not null,
  content_owner_address char(42),
  votes_contract_address char(42),
  treasury_contract_address char(42),
  content_register_fee_amount decimal(78,0) not null default 0,
  content_update_fee_amount decimal(78,0) not null default 0,
  edit_lock_votes decimal(78,0) not null default 0,
  is_allow_delete_after_vote smallint not null default 0,
  max_versions_per_content bigint not null default 0,
  treasury_owner_address char(42),
  epoch_budget_amount decimal(78,0) not null default 0,
  epoch_spent_amount decimal(78,0) not null default 0,
  timelock_min_delay_second bigint not null default 0,
  governor_token_address char(42),
  late_quorum_vote_extension_block bigint not null default 0,
  proposal_threshold_amount decimal(78,0) not null default 0,
  proposal_fee_amount decimal(78,0) not null default 0,
  voting_delay_block bigint not null default 0,
  voting_period_block bigint not null default 0,
  activation_blocks bigint not null default 0,
  cooldown_seconds bigint not null default 0,
  create_time timestamp not null default current_timestamp,
  update_time timestamp not null default current_timestamp,
  constraint pk_system_snapshot primary key (id),
  constraint uk_system_snapshot_snapshot_key unique (snapshot_key),
  constraint chk_system_snapshot_is_allow_delete_after_vote
    check (is_allow_delete_after_vote in (0,1))
);
