export const ADMIN_COPY = {
  navLabel: "Admin",
  dashboard: {
    eyebrow: "Admin",
    title: "联盟节点管理",
    description: "集中处理普通节点和验证者节点的加入申请，并通过 Besu 管理 RPC 完成审批动作。",
    nodeTitle: "普通节点申请",
    nodeDescription: "审核新的联盟成员节点，加入 Besu 节点白名单。",
    validatorTitle: "验证者申请",
    validatorDescription: "审核已接入节点的验证者资格申请，并向现有验证者发送投票。",
  },
  common: {
    authenticateFirst: "请先完成钱包身份验证",
    loadFailed: "加载申请列表失败",
    submitFailed: "提交申请失败",
    approveFailed: "批准失败",
    rejectFailed: "拒绝失败",
    refresh: "刷新",
    connectPrompt: "请先连接钱包并完成身份验证。",
    reviewActions: "审批操作",
    reviewPending: "待审批",
    reviewApproved: "已批准",
    reviewRejected: "已拒绝",
    applicant: "申请人",
    reviewer: "审批人",
    createdAt: "创建时间",
    updatedAt: "更新时间",
    status: "状态",
    noRequests: "当前没有申请记录",
    reviewCommentPlaceholder: "可选：填写审批备注",
    approve: "批准",
    reject: "拒绝",
    submit: "提交申请",
    viewerOnly: "当前地址可以查看自己的申请记录，但不能审批。",
    submitSuccess: "申请已提交",
    approveSuccess: "申请已批准",
    rejectSuccess: "申请已拒绝",
    adminOnly: "只有管理员地址可以审批申请。",
    signedInAs: "当前身份",
    unauthenticated: "未完成身份验证",
  },
  node: {
    eyebrow: "Nodes",
    title: "普通节点申请",
    description: "申请加入联盟网络的节点白名单。审批通过后，后台会调用 Besu permissioning API 把节点加入 allowlist。",
    nodeName: "节点名称",
    serverIp: "服务器地址",
    enode: "节点 enode",
  },
  validator: {
    eyebrow: "Validators",
    title: "验证者申请",
    description: "申请加入 QBFT 验证者集合。审批通过后，后台会先确保节点已加入 allowlist，再向现有验证者发送投票。",
    nodeName: "节点名称",
    serverIp: "服务器地址",
    enode: "节点 enode",
    validatorAddress: "验证者地址",
    voteSummary: "投票结果",
  },
} as const;
